name: Python Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        include:
          - os: ubuntu-latest
            python-version: 3.3
          - os: ubuntu-latest
            python-version: 3.4

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Update packaging tools
      run: |
        python -m pip install --upgrade pip setuptools
        pip install wheel
    - name: Unit Tests
      run: python -m unittest discover ambuild2 "*_test.py"
    - name: Install AMBuild
      run: pip install ./
    - name: Activate Visual Studio DevCMD
      if: ${{ matrix.os == 'windows-latest' }}
      uses: ilammy/msvc-dev-cmd@v1.3.0
      with:
        arch: x64
    - name: 'Test runtime API #1'
      uses: WildCard65/invoke-ambuild@v1.1-fin
      with:
        auto-install: false
        build-folder: objdir
        project-root: tests/staticlib
        delete-build: true
    - name: 'Test runtime API #2'
      uses: WildCard65/invoke-ambuild@v1.1-fin
      with:
        auto-install: false
        build-folder: objdir
        project-root: tests/modules
        delete-build: true
